### ISSUE TITLE
Progress reporting

### ISSUE THREAD

**Issue by stackotter** [saagarjha/unxip#13]
Progress reporting is very useful when unxipping large files (such as Xcode), especially on devices where it takes a long time. Would it be possible to add some kind of progress reporting to this tool?

**Comment by saagarjha** [comment]
unxip should run fast enough that it shouldn't take very long, so there's no need for progress reporting ;) Just kidding, I've been thinking of adding a SIGINFO handler for a while. One complication is that since I stream the xip I don't know things like how many files are in it beforehand, so reporting progress will require a bit of thought.

**Comment by stackotter** [comment]
Okay, that makes sense 👍

Could you possibly keep track of how many compressed bytes have been decompressed and use that as a rough estimate of how much remains? That way you don't need to know or estimate the number of files. The progress could just be the percentage of the file has been decompressed.

**Comment by saagarjha** [comment]
Yeah, that sounds reasonable.

**Comment by saagarjha** [comment]
You should be able to hit ⌃T at any time to get statistics about current progress now

**Comment by stackotter** [comment]
Awesome, thanks! I’ll be updating right away :) Great quality of life improvement 🚀
